[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
requires-python = ">=3.8"
name = "zernike-algorithm"
version = "0.0.1"

[project.optional-dependencies]
tests = ["pytest"]

[tool.ruff]
select = ["E", "F", "W", "B", "I", "RUF", "UP"]
ignore = ["E741"]
